

export const PolicesData = [
   {
    id: 1,
    hammer: "/images/hammer.svg",
    actionBtn: "URGENT ACTION",
    title: "Code of Conduct",
    details: "Standard operating procedures for professional behavior, ethics,",
    update:"Version", 
    updateNumber:"V4.2.0",
    lastUpdate:"LAST UPDATE",
    Date:"Oct 12, 2023",
    viewBtn: "View PDF",
    pdfIcon: "/images/pdf.svg",
    downloadIcon: "/images/downloadicon.svg",
    shareIcon: "/images/shareicon.svg",
  },
    {
    id: 2,
    hammer: "/images/hammer.svg",
    actionBtn: "URGENT ACTION",
    title: "Travel Policy",
    details: "Standard operating procedures for professional behavior, ethics,",
    update:"Version", 
    updateNumber:"V4.2.0",
    lastUpdate:"LAST UPDATE",
    Date:"Oct 12, 2023",
    viewBtn: "View PDF",
    pdfIcon: "/images/pdf.svg",
    downloadIcon: "/images/downloadicon.svg",
    shareIcon: "/images/shareicon.svg",
  },
    {
    id: 3,
    hammer: "/images/hammer.svg",
    actionBtn: "URGENT ACTION",
    title: "Leave Policy",
    details: "Standard operating procedures for professional behavior, ethics,",
    update:"Version", 
    updateNumber:"V4.2.0",
    lastUpdate:"LAST UPDATE",
    Date:"Oct 12, 2023",
    viewBtn: "View PDF",
    pdfIcon: "/images/pdf.svg",
    downloadIcon: "/images/downloadicon.svg",
    shareIcon: "/images/shareicon.svg",
  },
    {
    id: 4,
    hammer: "/images/hammer.svg",
    actionBtn: "URGENT ACTION",
    title: "Information Security",
    details: "Standard operating procedures for professional behavior, ethics,",
    update:"Version", 
    updateNumber:"V4.2.0",
    lastUpdate:"LAST UPDATE",
    Date:"Oct 12, 2023",
    viewBtn: "View PDF",
    pdfIcon: "/images/pdf.svg",
    downloadIcon: "/images/downloadicon.svg",
    shareIcon: "/images/shareicon.svg",
  },
    {
    id: 5,
    hammer: "/images/hammer.svg",
    actionBtn: "URGENT ACTION",
    title: "Remote Work Policy",
    details: "Standard operating procedures for professional behavior, ethics,",
    update:"Version", 
    updateNumber:"V4.2.0",
    lastUpdate:"LAST UPDATE",
    Date:"Oct 12, 2023",
    viewBtn: "View PDF",
    pdfIcon: "/images/pdf.svg",
    downloadIcon: "/images/downloadicon.svg",
    shareIcon: "/images/shareicon.svg",
  },

]

