

export const PolicesData = [
   {
    id: 1,
    icon: "/images/filterIcon.svg",
    actionBtn: "URGENT ACTION",
    title: "Hello",
    details: "Trikuta",
    update:"Version", 
    updateNumber:"V4.2.0",
    lastUpdate:"LAST UPDATE",
    Date:"Oct 12, 2023",
    viewBtn: "View PDF",
    downloadIcon: "/images/download.svg",
    shareIcon: "/images/shareIcon.svg",
  },
    {
    id: 2,
    icon: "/images/filterIcon.svg",
    actionBtn: "URGENT ACTION",
    title: "Hello",
    details: "Trikuta",
    update:"Version", 
    updateNumber:"V4.2.0",
    lastUpdate:"LAST UPDATE",
    Date:"Oct 12, 2023",
    viewBtn: "View PDF",
    downloadIcon: "/images/download.svg",
    shareIcon: "/images/shareIcon.svg",
  },
    {
    id: 3,
    icon: "/images/filterIcon.svg",
    actionBtn: "URGENT ACTION",
    title: "Hello",
    details: "Trikuta",
    update:"Version", 
    updateNumber:"V4.2.0",
    lastUpdate:"LAST UPDATE",
    Date:"Oct 12, 2023",
    viewBtn: "View PDF",
    downloadIcon: "/images/download.svg",
    shareIcon: "/images/shareIcon.svg",
  },
    {
    id: 4,
    icon: "/images/filterIcon.svg",
    actionBtn: "URGENT ACTION",
    title: "Hello",
    details: "Trikuta",
    update:"Version", 
    updateNumber:"V4.2.0",
    lastUpdate:"LAST UPDATE",
    Date:"Oct 12, 2023",
    viewBtn: "View PDF",
    downloadIcon: "/images/download.svg",
    shareIcon: "/images/shareIcon.svg",
  },
    {
    id: 5,
    icon: "/images/filterIcon.svg",
    actionBtn: "URGENT ACTION",
    title: "Hello",
    details: "Trikuta",
    update:"Version", 
    updateNumber:"V4.2.0",
    lastUpdate:"LAST UPDATE",
    Date:"Oct 12, 2023",
    viewBtn: "View PDF",
    downloadIcon: "/images/download.svg",
    shareIcon: "/images/shareIcon.svg",
  },
    {
    id: 6,
    icon: "/images/filterIcon.svg",
    actionBtn: "URGENT ACTION",
    title: "Hello",
    details: "Trikuta",
    update:"Version", 
    updateNumber:"V4.2.0",
    lastUpdate:"LAST UPDATE",
    Date:"Oct 12, 2023",
    viewBtn: "View PDF",
    downloadIcon: "/images/download.svg",
    shareIcon: "/images/shareIcon.svg",
  },
]

